# Generated by Django 5.0.3 on 2024-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='poem',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
