# Generated by Django 5.0.3 on 2024-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_poem_likes_alter_like_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='poems', to='accounts.comment'),
        ),
    ]
