# Generated by Django 5.0.3 on 2024-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='path/to/default/avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
