# Generated by Django 5.0.3 on 2024-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='D:\\Django\\poem_platform\x07ccounts\\static\x07vatar.png', null=True, upload_to='avatars/'),
        ),
    ]
